/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Logica.Categoria;
import Logica.ControladorJuego;
import Logica.ControladorPerfil;
import javax.swing.JOptionPane;
/**
 *
 * @author dc
 */
public class AltaCategoria extends javax.swing.JFrame {

    /**
     * Creates new form Categoria
     */
    public AltaCategoria() {
        initComponents();
        
         limpiar();
          setLocationRelativeTo(null);
    }
   Categoria cat= new Categoria();
   ControladorJuego cont1 = ControladorJuego.getInstance();
   
    
void limpiar(){
    text1.setText("");
}
boolean verificarCampos(){
    if(text1.getText().trim().length()==0){

    return false;
    }else{
        return true;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        b_Cancelar = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(745, 453));
        setMinimumSize(new java.awt.Dimension(745, 453));
        setPreferredSize(new java.awt.Dimension(745, 453));
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Nombre");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(33, 87, 49, 17);

        text1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });
        text1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text1KeyTyped(evt);
            }
        });
        getContentPane().add(text1);
        text1.setBounds(100, 86, 507, 30);

        b_Cancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b_Cancelar.setForeground(new java.awt.Color(0, 51, 102));
        b_Cancelar.setText("Cancelar");
        b_Cancelar.setPreferredSize(new java.awt.Dimension(90, 30));
        b_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(b_Cancelar);
        b_Cancelar.setBounds(569, 348, 90, 30);

        boton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boton1.setForeground(new java.awt.Color(0, 51, 102));
        boton1.setText("Aceptar");
        boton1.setPreferredSize(new java.awt.Dimension(90, 30));
        boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton1MouseClicked(evt);
            }
        });
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        boton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boton1KeyPressed(evt);
            }
        });
        getContentPane().add(boton1);
        boton1.setBounds(453, 348, 90, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Alta de Categoria");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 297, 48);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 960, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
if(cont1.ingresarCat(text1.getText())==true){
   JOptionPane.showMessageDialog(null, "Esa categoria ya existe");
     
}else{
    text1.transferFocus();
}

        
     
    }//GEN-LAST:event_text1ActionPerformed

    private void text1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text1KeyTyped

    private void b_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CancelarActionPerformed
          this.setVisible(false);
      Inicio view;
        view = new Inicio();
      view.setVisible(true); 
    }//GEN-LAST:event_b_CancelarActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        String nombre; 

        
      if(verificarCampos()==true){
          nombre= text1.getText();
           /////////////////////////////////guardamos en la base de datos//////////////////////////////////////////////
         if(cont1.ingresarCat(text1.getText())==true){
             JOptionPane.showMessageDialog(null, "Esa categoria ya existe");
         }else{
           cont1.crearCategoria(nombre); 
           this.setVisible(false);
           Inicio view;
           view = new Inicio();
           view.setVisible(true);
         }

      }else{
          JOptionPane.showMessageDialog(null, "Complete el campo");      
   
      }
        
    }//GEN-LAST:event_boton1ActionPerformed
//
    private void boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseClicked
//       String a = text1.getText();
//        try {
//            if(cc.existeCategoria(a)==true){
//        JOptionPane.showMessageDialog(null, "Esa categoria ya existe");      
//   
//                
//            } 
//        } catch (SQLException ex) {
//            Logger.getLogger(AltaCategoria.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_boton1MouseClicked

    private void boton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boton1KeyPressed
        // TODO add your handling code here
    }//GEN-LAST:event_boton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AltaCategoria().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Cancelar;
    private javax.swing.JButton boton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField text1;
    // End of variables declaration//GEN-END:variables
}
