/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import java.awt.Toolkit;

import Persistencia.conectar;
import Logica.Cliente;
import Logica.ControladorPerfil;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Logica.Datatypes.DataFecha;
import Logica.Desarrollador;
import Presentacion.AltaPerfil2;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicole
 */
public class AltaPerfil extends javax.swing.JFrame {
    
ControladorPerfil control2= ControladorPerfil.getInstance();
    /**
     * Creates new form AltaPerfil
     */
    DefaultTableModel model;
    public AltaPerfil() {
       
        initComponents();
        limpiar();
         setLocationRelativeTo(null);
        
       
       
        
            
    }
    conectar cc=new conectar();
//      void cargar (){
//        String [] titulos = {"Nick","Correo","Nombre","Apellido","FechaNacimiento",
//            "Edad","Imagen","Tipo","URL"} ;
//        String [] registros = new String [9];
//        
//        String sql = "SELECT * FROM perfiles";
//        model = new DefaultTableModel (null, titulos);
//        
//        Connection cn = cc.conectar();
//                
//        try {
//          Statement  st = cn.createStatement();
//          ResultSet rs = st.executeQuery(sql);
//             
//             while (rs.next()){
//                 registros[0] = rs.getString("Nick");
//                 registros[1] = rs.getString("Correo");
//                 registros[2] = rs.getString("Nombre");
//                 registros[3] = rs.getString("Apellido");
//                 registros[4] = rs.getString("FechaNacimiento");
//                 registros[5] = rs.getString("Edad");
//                 registros[6] = rs.getString("Imagen");
//                 registros[7] = rs.getString("Tipo");                 
//                 registros[8] = rs.getString("webURL");
//                 
//                 model.addRow(registros);
//                 
//             } 
//             t_perfiles.setModel(model);
//             
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog (null, ex);
//        }
//       
//        
//        
//        
//}
    



        
 
    

//
//void desbloquear(){
//   
//    
////    b_nuevo.setEnabled(false);
//    
//}
////*****************funcion para pasar el date java a date MySQL********************** 
//public String dateToMySQLDate(DataFecha fecha)
//{
//  java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
//  return sdf.format(fecha);
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        botones_grupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_nick = new javax.swing.JTextField();
        t_correo = new javax.swing.JTextField();
        b_aceptar = new javax.swing.JButton();
        b_Cancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        existeCorreo = new javax.swing.JLabel();
        existeNick = new javax.swing.JLabel();

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Imagen");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(745, 453));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Alta perfil");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 360, 80);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Nick");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 180, 50, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Correo electrónico");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 240, 180, 20);

        t_nick.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t_nick.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        t_nick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nickActionPerformed(evt);
            }
        });
        t_nick.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_nickFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_nickFocusLost(evt);
            }
        });
        t_nick.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                t_nickInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        t_nick.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_nickKeyTyped(evt);
            }
        });
        getContentPane().add(t_nick);
        t_nick.setBounds(260, 180, 260, 30);

        t_correo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_correoActionPerformed(evt);
            }
        });
        t_correo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_correoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_correoFocusLost(evt);
            }
        });
        getContentPane().add(t_correo);
        t_correo.setBounds(260, 240, 260, 30);

        b_aceptar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b_aceptar.setForeground(new java.awt.Color(0, 51, 102));
        b_aceptar.setText("Aceptar");
        b_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(b_aceptar);
        b_aceptar.setBounds(510, 370, 90, 30);

        b_Cancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b_Cancelar.setForeground(new java.awt.Color(0, 51, 102));
        b_Cancelar.setText("Cancelar");
        b_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(b_Cancelar);
        b_Cancelar.setBounds(620, 370, 90, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-10, 0, 990, 470);

        existeCorreo.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(existeCorreo);
        existeCorreo.setBounds(350, 270, 190, 20);

        existeNick.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(existeNick);
        existeNick.setBounds(360, 210, 160, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_nickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nickActionPerformed
      t_nick.transferFocus();
      Cliente c=new Cliente();
      Desarrollador d=new Desarrollador();
      if(!"".equals(t_nick.getText())&&(c.existeN(t_nick.getText())||d.existeN(t_nick.getText()))){
          existeNick.setVisible(true);
          existeNick.setText("Este nick ya se ha utilizado.");
      }
      else
          existeNick.setVisible(false);
     
    
    }//GEN-LAST:event_t_nickActionPerformed


    

    private void t_nickKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nickKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nickKeyTyped

    private void t_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_correoActionPerformed
     t_correo.transferFocus();
     Cliente c=new Cliente();
      Desarrollador d=new Desarrollador();
      if(!"".equals(t_correo.getText())&&(c.existeC(t_correo.getText())||d.existeC(t_correo.getText()))){
          existeCorreo.setVisible(true);
          existeCorreo.setText("Este correo ya se ha utilizado.");
      }
      else
          existeCorreo.setVisible(false);
     
     
    }//GEN-LAST:event_t_correoActionPerformed

    private void b_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CancelarActionPerformed
         this.setVisible(false);
      Inicio view;
        view = new Inicio();
      view.setVisible(true); 
    }//GEN-LAST:event_b_CancelarActionPerformed

    private void b_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aceptarActionPerformed
if(!"".equals(t_correo.getText()) && !"".equals(t_nick.getText())){
       if(verificarCampos()){
        boolean r= control2.altaPerfil(t_nick.getText(), t_correo.getText());
        if(r==true){
           JOptionPane.showMessageDialog(null, "El nick o correo ingresados ya existen en el sistema","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            control2.setCorreoAux(t_correo.getText());
            control2.setNickAux(t_nick.getText());
             this.setVisible(false);
             AltaPerfil2 view = new AltaPerfil2();
             view.setVisible(true);
        }
       }
}

//        String img="",url=null;
//        String tipo;
//        if(verificarCampos()==true){
//            String ni= t_nick.getText();
//            String ape=t_apellido.getText();
//            String nom=t_nombre.getText();
//            String corr=t_correo.getText();
//            img=t_imagen.getText();
//            DataFecha fecha= obtenerFecha();
//
//            /////////////////////////////////guardamos en la base de datos//////////////////////////////////////////////
//            if(r_cliente.isSelected()){
//                tipo="Cliente";
//                Cliente cli=new Cliente(ni,corr,nom,ape,fecha,img);
//                cli.addCliente();
//            }
//            else{
//                tipo="Desarrollador";
//                url=t_sitioweb.getText();
//                Desarrollador des=new Desarrollador();
//                des.addDesarrollador();
//
//            }
//
//        }
    }//GEN-LAST:event_b_aceptarActionPerformed

    private void t_nickInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_t_nickInputMethodTextChanged

    }//GEN-LAST:event_t_nickInputMethodTextChanged

    private void t_nickFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_nickFocusGained
           existeNick.setVisible(false);
        
    }//GEN-LAST:event_t_nickFocusGained

    private void t_nickFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_nickFocusLost
     
      Cliente c=new Cliente();
      Desarrollador d=new Desarrollador();
      if(!"".equals(t_nick.getText())&&(c.existeN(t_nick.getText())||d.existeN(t_nick.getText()))){
          existeNick.setVisible(true);
          existeNick.setText("Este nick ya se ha utilizado.");
      }
      else
          existeNick.setVisible(false);
     
     
    
    }//GEN-LAST:event_t_nickFocusLost

    private void t_correoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_correoFocusGained
        existeCorreo.setVisible(false);
    }//GEN-LAST:event_t_correoFocusGained

    private void t_correoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_correoFocusLost
        Cliente c=new Cliente();
      Desarrollador d=new Desarrollador();
      if(!"".equals(t_correo.getText())&&(c.existeC(t_correo.getText())||d.existeC(t_correo.getText()))){
          existeCorreo.setVisible(true);
          existeCorreo.setText("Este correo ya se ha utilizado.");
      }
      else
          existeCorreo.setVisible(false);
    }//GEN-LAST:event_t_correoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaPerfil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Cancelar;
    private javax.swing.JButton b_aceptar;
    public javax.swing.ButtonGroup botones_grupo;
    private javax.swing.JLabel existeCorreo;
    private javax.swing.JLabel existeNick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField t_correo;
    private javax.swing.JTextField t_nick;
    // End of variables declaration//GEN-END:variables

/********************************************  F U N C I O N E S  ********************************************/ 
    
public boolean existeNick(){
    String ni= t_nick.getText();
    Cliente c=new Cliente();
    Desarrollador d=new Desarrollador();
    boolean r=false;
        
    if(!"".equals(t_nick.getText())){
       if(c.existeN(ni)==true){
            r=true;
       }
       else{
            if(d.existeN(ni)==true){
                 r=true;
            }
           }
                
      }
     return r;
}

public boolean existeCorreo(){
    String co= t_correo.getText();
    Cliente c=new Cliente();
    Desarrollador d=new Desarrollador();
    boolean r=false;
        
    if(!"".equals(t_correo.getText())){
       if(c.existeC(co)==true){
            r=true;
       }
       else{
            if(d.existeC(co)==true){
                 r=true;
            }
           }
                
      }
     return r;
}    

void limpiar(){
    t_nick.setText("");
    t_correo.setText("");
    
}

boolean verificarCampos(){
    if(t_nick.getText().trim().length()==0||t_correo.getText().trim().length()==0){
        JOptionPane.showMessageDialog(null, "Todos los campos obligatorios deben ser completados","Error",JOptionPane.ERROR_MESSAGE);
        return false;
    }
    else
         return true;
    }


}


