/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Busqueda;
import Logica.ControladorJuego;
import Logica.ControladorPerfil;
import Logica.Datatypes.DataP;
import Logica.Datatypes.dataDes;
import Logica.Datatypes.infoCat;
import Logica.Desarrollador;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Administrador
 */
public class AltaJuego2 extends javax.swing.JFrame {
DefaultListModel modell = new DefaultListModel();
DefaultListModel modell2 = new DefaultListModel();
DefaultComboBoxModel modelo = new DefaultComboBoxModel();
List listaa = new ArrayList();
    ControladorPerfil cont2= ControladorPerfil.getInstance();
        ControladorJuego cont1= ControladorJuego.getInstance();
         Busqueda busqueda=new Busqueda();
    /**
     * Creates new form AltaJuego2
     */
    public AltaJuego2() throws SQLException {
        initComponents();
         setLocationRelativeTo(null);
        
//         ControladorPerfil cont2= ControladorPerfil.getInstance();
//        ControladorJuego cont1= ControladorJuego.getInstance();
   
         /******Listo todos los desarrolladores del sistema *****/
//          Iterator it = cont.iterator();
// while (it2.hasNext()){
//dataDes desarrollador = (dataDes) it2.next();
//modelo.addElement(desarrollador.getNick());
// }
// l_desarrolladores.setModel(modelo);
//    }
//    
Iterator it1 = cont1.VerCategoriasCargadas().iterator();
while (it1.hasNext()){
    infoCat cate=new infoCat();
    cate = (infoCat)it1.next();
   
   
modell.addElement(cate.getNombre());
 }
 lista1.setModel(modell);
    
    
 
 
 
 c_desarrolladores.getEditor().getEditorComponent().addKeyListener(new KeyAdapter(){
       
           @Override
         public void  keyReleased(KeyEvent evt){
           
         String cadenaEscrita=c_desarrolladores.getEditor().getItem().toString();
         //limitar los eventos de las teclas usando el ACII 
         if(evt.getKeyCode()>=65 && evt.getKeyCode()<=90 || evt.getKeyCode()>=96 && evt.getKeyCode()<=105 || evt.getKeyCode()==8 ){
             try {            
                 c_desarrolladores.setModel(busqueda.getListaDesarrolladores(cadenaEscrita));
                 if(c_desarrolladores.getItemCount()>0){
                     c_desarrolladores.showPopup();
                     if(evt.getKeyCode()!=8){
                         ((JTextComponent)c_desarrolladores.getEditor().getEditorComponent()).select(cadenaEscrita.length(),c_desarrolladores.getEditor().getItem().toString().length());
                         
                     }
                     else{
                         c_desarrolladores.getEditor().setItem(cadenaEscrita);
                     }
                 }
                 else{
                     c_desarrolladores.addItem(cadenaEscrita);
                 }
             } catch (SQLException ex) {
                 Logger.getLogger(ConsultaPerfil.class.getName()).log(Level.SEVERE, null, ex);
             }
             
             
             
         }
             
             
       }
         
         
           
       
       });
    }
public void CargarComboBox(){
    List al=cont2.listarP();
    Iterator it = al.iterator();
  
       while(it.hasNext()){  
            DataP a=(DataP)it.next();
                
               modelo.addElement(a.getNick());
               
            }
            c_perfiles.setModel(modelo); 

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lista1 = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista2 = new javax.swing.JList();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        c_desarrolladores = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(756, 453));
        setMinimumSize(new java.awt.Dimension(756, 453));
        setPreferredSize(new java.awt.Dimension(756, 453));
        getContentPane().setLayout(null);

        lista1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista1MouseClicked(evt);
            }
        });
        lista1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lista1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 120, 149, 120);

        jScrollPane1.setViewportView(lista2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(360, 120, 149, 120);

        boton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boton1.setForeground(new java.awt.Color(0, 51, 102));
        boton1.setText("Seleccionar");
        boton1.setPreferredSize(new java.awt.Dimension(93, 10));
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton1);
        boton1.setBounds(190, 160, 100, 20);

        boton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boton2.setForeground(new java.awt.Color(0, 51, 102));
        boton2.setText("Eliminar");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        getContentPane().add(boton2);
        boton2.setBounds(520, 160, 90, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 370, 90, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Alta de Juego");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 232, 48);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Categorias Seleccionadas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 90, 170, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Nick Desarrollador");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 320, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Seleccione las categorias");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 90, 170, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 102));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(630, 370, 90, 30);

        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setMaximumSize(new java.awt.Dimension(745, 456));
        jLabel5.setMinimumSize(new java.awt.Dimension(745, 456));
        jLabel5.setPreferredSize(new java.awt.Dimension(745, 456));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 960, 490);

        c_desarrolladores.setEditable(true);
        c_desarrolladores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c_desarrolladoresMouseClicked(evt);
            }
        });
        c_desarrolladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_desarrolladoresActionPerformed(evt);
            }
        });
        getContentPane().add(c_desarrolladores);
        c_desarrolladores.setBounds(220, 320, 242, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lista1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lista1MouseClicked

    private void lista1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista1ValueChanged

    }//GEN-LAST:event_lista1ValueChanged

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed

        if(lista1.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "No seleciono ninguna categoria");
        }else{
            String elem=lista1.getSelectedValue().toString();
            int indice = lista1.getSelectedIndex();
            
            modell2.addElement(elem);
            lista2.setModel(modell2);
            modell.remove(indice);
            lista1.setModel(modell);
            listaa.add(elem);
           cont1.categoriasparaeljuego.add(elem);
        }

    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        if(lista2.getSelectedIndex()== -1){
            JOptionPane.showMessageDialog(null, "No seleciono ninguna categoria");
        }else{
            String elem=lista2.getSelectedValue().toString();
            int indice = lista2.getAnchorSelectionIndex();

            modell.addElement(elem);
            lista2.setModel(modell2);
            modell2.remove(indice);
            lista1.setModel(modell);
          listaa.remove(elem);
            
             cont1.categoriasparaeljuego.remove(elem);
        }
    }//GEN-LAST:event_boton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
      String nom, desc,nick;
      ControladorPerfil cont2= ControladorPerfil.getInstance();
      ControladorJuego cont1 = ControladorJuego.getInstance();

      
       nick= (String )c_desarrolladores.getSelectedItem(); 
        cont2.SelecDes(nick);
       Desarrollador des = cont2.GetDes();
       cont1.registrarJ(des);
       

    } catch (SQLException ex) {
        Logger.getLogger(AltaJuego2.class.getName()).log(Level.SEVERE, null, ex);
    }
    this.setVisible(false);
Inicio vista = new Inicio();
vista.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 this.setVisible(false);
      Inicio view;
        view = new Inicio();
      view.setVisible(true); 
                                       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void c_desarrolladoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_desarrolladoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c_desarrolladoresMouseClicked

    private void c_desarrolladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_desarrolladoresActionPerformed
        //String d = combo1.getComponents().toString();
        //        dataPerfil dp= cont2.selecPerfil(d);
        //        jLabel8.setText(dp.nombre);

    }//GEN-LAST:event_c_desarrolladoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AltaJuego2().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AltaJuego2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JComboBox c_desarrolladores;
    private javax.swing.JComboBox c_perfiles;
    private javax.swing.JComboBox c_perfiles1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lista1;
    private javax.swing.JList lista2;
    // End of variables declaration//GEN-END:variables
}
