/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Persistencia.conectar;
import Logica.Categoria;
import Logica.Datatypes.Money;
import Logica.Datatypes.infoCat;
import Logica.Desarrollador;
import Logica.ControladorJuego;
import Logica.ControladorPerfil;
import Logica.Datatypes.dataDes;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Array;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author dc
 */
public class AltaJuego extends javax.swing.JFrame {
DefaultListModel modell = new DefaultListModel();
DefaultListModel modell2 = new DefaultListModel();
DefaultComboBoxModel modelo = new DefaultComboBoxModel();
List listaa = new ArrayList();
    /**
     * Creates new form AltaJuego
     */
    /**************LAURA***************/
    public AltaJuego() throws SQLException  {
        
         initComponents();
         

          setLocationRelativeTo(null);
          // ControladorJuego cont= ControladorJuego.getInstance();
           ControladorPerfil cont2= ControladorPerfil.getInstance();
           
//       Iterator it = cc.ListaCategorias().iterator();                  // Lista todas las categorias del sistema
//       while(it.hasNext()){               
//                Object categorias = it.next();
//               modell.addElement(categorias);
//            }
//            lista1.setModel(modell);           
            
            

 
 
 
            
            
    }
  
    /******** TERMINA LAURAA **********************/
    conectar cc= new conectar();
          Connection cn = cc.conexion();
          ControladorJuego cont= ControladorJuego.getInstance();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_tamanio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_precio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        t_nombre = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_descripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 153, 153));
        setMinimumSize(new java.awt.Dimension(745, 453));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 49, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Alta de Juego");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 232, 48);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Tamaño (KB)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 140, 90, 30);

        t_tamanio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        t_tamanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_tamanioActionPerformed(evt);
            }
        });
        t_tamanio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_tamanioKeyTyped(evt);
            }
        });
        getContentPane().add(t_tamanio);
        t_tamanio.setBounds(80, 140, 111, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Precio U$S");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 190, 120, 30);

        t_precio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        t_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_precioActionPerformed(evt);
            }
        });
        t_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_precioKeyTyped(evt);
            }
        });
        getContentPane().add(t_precio);
        t_precio.setBounds(80, 190, 111, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Descripción");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 100, 70, 17);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 360, 90, 30);

        t_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        t_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nombreActionPerformed(evt);
            }
        });
        t_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(t_nombre);
        t_nombre.setBounds(80, 90, 111, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 102));
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(620, 360, 90, 30);

        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1030, 520);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 102));
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(510, 360, 90, 30);

        t_descripcion.setColumns(20);
        t_descripcion.setRows(5);
        jScrollPane1.setViewportView(t_descripcion);
        t_descripcion.setLineWrap(true);
        t_descripcion.setWrapStyleWord(true);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(330, 100, 380, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_tamanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_tamanioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_tamanioActionPerformed

    private void t_tamanioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_tamanioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t_tamanioKeyTyped

    private void t_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_precioActionPerformed

    private void t_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_precioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t_precioKeyTyped
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String nom, desc,nick;
   int id = 0;
    double tamanio;
    String tam;
//   //Desarrollador des = new Desarrollador();
    double pr;
    String pre;
//          
//  
        nom= t_nombre.getText();
        desc=t_descripcion.getText();
//            nick= (String )l_desarrolladores.getSelectedItem(); // CAMBIAAAAR
       tam =  t_tamanio.getText();
       tamanio = Double.parseDouble(tam);
       pre = t_precio.getText();
       pr = Double.parseDouble(pre); 
       Money precio = new Money(pr,'d');
    try {
       
     List vacia = new ArrayList();
     Desarrollador des = new Desarrollador();
     cont.RecordarDatosJuegos(nom, precio, desc,tamanio,id,des,vacia,vacia,vacia );
     cont.CargarCategorias(cont.AltaJuego(nom,tamanio,precio,desc)); 
     this.setVisible(false);
     AltaJuego2 view;
     view = new AltaJuego2();
     view.setVisible(true)      ;
                
                    // Agrego el nuevo juego con su desarrollador
        //            
        //            //Agrego las categorias del juego;
        //        Iterator it = listaa.iterator();
        //        while (it.hasNext()){
        //            String elemto = (String) it.next();
        //           //JOptionPane.showMessageDialog(null, elemto);
        //         try {
        //             cc.AgregarCategoriaAJuego(nom, elemto); 
        //         } catch (SQLException ex) {
        //         }
        //         }
    } catch (SQLException ex) {
        Logger.getLogger(AltaJuego.class.getName()).log(Level.SEVERE, null, ex);
    }
          
        
        
        
    
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nombreActionPerformed

    private void t_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nombreKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 this.setVisible(false);
      Inicio view;
        view = new Inicio();
      view.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
         
        java.awt.EventQueue.invokeLater(new Runnable() {
          
            public void run() {
                try {
                    //   try {
                           new AltaJuego().setVisible(true);
                          
                 //     } catch (SQLException ex) {
                    //   }
                    //   }
                } catch (SQLException ex) {
                    Logger.getLogger(AltaJuego.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea t_descripcion;
    private javax.swing.JTextField t_nombre;
    private javax.swing.JTextField t_precio;
    private javax.swing.JTextField t_tamanio;
    // End of variables declaration//GEN-END:variables
}
