/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Busqueda;
import Logica.Cliente;
import Logica.ControladorJuego;
import Logica.Datatypes.DataFecha;
import Logica.Datatypes.infoComp;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Nicole
 */
public class ComprarJuego2 extends javax.swing.JFrame {
 Busqueda busqueda=new Busqueda();
    /**
     * Creates new form ComprarJuego2
     */
    public ComprarJuego2() {
        initComponents();
         setLocationRelativeTo(null);
           c_perfiles.getEditor().getEditorComponent().addKeyListener(new KeyAdapter(){
       
           @Override
         public void  keyReleased(KeyEvent evt){
           
         String cadenaEscrita=c_perfiles.getEditor().getItem().toString();
         //limitar los eventos de las teclas usando el ACII 
         if(evt.getKeyCode()>=65 && evt.getKeyCode()<=90 || evt.getKeyCode()>=96 && evt.getKeyCode()<=105 || evt.getKeyCode()==8 ){
             try {            
                 c_perfiles.setModel(busqueda.getListaClientes(cadenaEscrita));
                 if(c_perfiles.getItemCount()>0){
                     c_perfiles.showPopup();
                     if(evt.getKeyCode()!=8){
                         ((JTextComponent)c_perfiles.getEditor().getEditorComponent()).select(cadenaEscrita.length(),c_perfiles.getEditor().getItem().toString().length());
                         
                     }
                     else{
                         c_perfiles.getEditor().setItem(cadenaEscrita);
                     }
                 }
                 else{
                     c_perfiles.addItem(cadenaEscrita);
                 }
             } catch (SQLException ex) {
                 Logger.getLogger(ConsultaPerfil.class.getName()).log(Level.SEVERE, null, ex);
             }
             
             
             
         }
             
             
       }
         
         
           
       
       });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_dia = new javax.swing.JComboBox();
        t_mes = new javax.swing.JComboBox();
        t_anio = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Dia = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_dia1 = new javax.swing.JTextField();
        t_mes1 = new javax.swing.JTextField();
        t_anio1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c_perfiles = new javax.swing.JComboBox();
        b_aceptar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        t_dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        t_dia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_diaActionPerformed(evt);
            }
        });

        t_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        t_mes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_mesActionPerformed(evt);
            }
        });

        t_anio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013" }));
        t_anio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t_anio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_anioActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(745, 453));
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Nick cliente");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(133, 52, 67, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Fecha de la compra");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(125, 110, 119, 17);

        Dia.setForeground(new java.awt.Color(0, 51, 102));
        Dia.setText("Dia");
        jPanel2.add(Dia);
        Dia.setBounds(308, 90, 30, 14);

        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Mes");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(372, 90, 29, 14);

        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Año");
        jLabel6.setToolTipText("");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(460, 90, 52, 14);
        jPanel2.add(t_dia1);
        t_dia1.setBounds(298, 110, 30, 29);
        jPanel2.add(t_mes1);
        t_mes1.setBounds(372, 110, 29, 29);
        jPanel2.add(t_anio1);
        t_anio1.setBounds(442, 110, 50, 29);

        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("/");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(419, 110, 27, 29);

        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("/");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(346, 110, 20, 29);

        c_perfiles.setEditable(true);
        c_perfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c_perfilesMouseClicked(evt);
            }
        });
        c_perfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_perfilesActionPerformed(evt);
            }
        });
        jPanel2.add(c_perfiles);
        c_perfiles.setBounds(270, 50, 242, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 120, 640, 180);

        b_aceptar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b_aceptar.setForeground(new java.awt.Color(0, 51, 102));
        b_aceptar.setText("Aceptar");
        b_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(b_aceptar);
        b_aceptar.setBounds(520, 370, 90, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(630, 370, 90, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Comprar Juego");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 259, 48);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -20, 960, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_diaActionPerformed

    }//GEN-LAST:event_t_diaActionPerformed

    private void t_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_mesActionPerformed

    private void t_anioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_anioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_anioActionPerformed
boolean verificarCampos(){
    if(c_perfiles.getSelectedItem().toString().trim().length()==0){
        JOptionPane.showMessageDialog(null, "Debe ingresar el nick del cliente para poder continuar","Error",JOptionPane.ERROR_MESSAGE);
        return false;
    }
    else
         return true;
    }


    private void b_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aceptarActionPerformed
       if(!"".equals(c_perfiles.getSelectedItem().toString())){
       if(verificarCampos()){
           Cliente cli=new Cliente();
           if(cli.existeN(c_perfiles.getSelectedItem().toString())){
           ControladorJuego c1= ControladorJuego.getInstance();
           
           c1.realizarCompra(c_perfiles.getSelectedItem().toString(), obtenerFecha());
           this.setVisible(false);
           ComprarJuego3 view = new ComprarJuego3();
           view.setVisible(true);
       }
           else
                JOptionPane.showMessageDialog(null, "El nick o correo ingresados ya existen en el sistema","Error",JOptionPane.ERROR_MESSAGE);
       }
      }

    }//GEN-LAST:event_b_aceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
      Inicio view;
        view = new Inicio();
      view.setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c_perfilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_perfilesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_c_perfilesMouseClicked

    private void c_perfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_perfilesActionPerformed
        //String d = combo1.getComponents().toString();
        //        dataPerfil dp= cont2.selecPerfil(d);
        //        jLabel8.setText(dp.nombre);

    }//GEN-LAST:event_c_perfilesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprarJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprarJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprarJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprarJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprarJuego2().setVisible(true);
            }
        });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dia;
    private javax.swing.JButton b_aceptar;
    private javax.swing.JComboBox c_perfiles;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox t_anio;
    private javax.swing.JTextField t_anio1;
    private javax.swing.JComboBox t_dia;
    private javax.swing.JTextField t_dia1;
    private javax.swing.JComboBox t_mes;
    private javax.swing.JTextField t_mes1;
    // End of variables declaration//GEN-END:variables

    
    public DataFecha obtenerFecha(){
            String ddd = (String) t_dia1.getText();
            String mmm = (String) t_mes1.getText();
            String aaa = (String) t_anio1.getText();
            int dd=Integer.parseInt(ddd);
            int aa=Integer.parseInt(aaa);
            int mm=Integer.parseInt(mmm);
            DataFecha fecha = new DataFecha(dd,mm,aa);
            return fecha;
           
}
    
    public boolean mostrarFechaCorrecta(){
        
    Calendar fechaActual = Calendar.getInstance();
 
    int anios = fechaActual.get(Calendar.YEAR);
    int meses = fechaActual.get(Calendar.MONTH);
    int dias = fechaActual.get(Calendar.DAY_OF_MONTH);
        
    String ddd = (String) t_dia1.getText();    
    String mmm = (String) t_mes1.getText();      
    String aaa = (String) t_anio1.getText();   
    int dd=Integer.parseInt(ddd);       
    int aa=Integer.parseInt(aaa);
    int mm=Integer.parseInt(mmm);
        
    
    if(aa <= anios && aa>= 1900){
        if(mm == 1 || mm == 3 || mm == 5 || mm == 7 || mm == 8 || mm == 10 || mm == 12){
            if((dd >= 1 && dd <= 31) && aa != anios){
                return true;
            }
            else{
                if(aa == anios && mm <= meses && dd < dias){
                    return true;
                }
                else{
                    if(aa == anios && mm < meses){
                        return true;
                    }
                    else{
                        return false;
                    }
                }
            }
        }
        else{
            if(mm == 4 || mm == 6 || mm == 9 || mm == 11){
                if((dd >= 1 && dd <= 30) && aa != anios){
                    return true;
                }
                else{
                    if(aa == anios && mm == meses && dd < dias){
                        return true;
                    }
                    else{
                        if(aa == anios && mm < meses){
                            return true;
                        }
                        else{
                            return false;
                        }
                    }
                }
            }
            else{
                if(mm == 2){
                    if((dd >= 1 && dd <= 29) && aa != anios){
                        return true;
                    }
                    else{
                        if(aa == anios && mm == meses && dd <= dias){
                            return true;
                        }
                        else{
                            if(aa == anios && mm < meses){
                                return true;
                            }
                            else{
                                return false;
                            }
                        }
                    }
                }
                else{
                    return false;
                }
            }
        }
    }
    else{
        return false;
    }  
    }
}





